"""empty message

Revision ID: 1fc91765e37f
Revises: 29f34eda35d8
Create Date: 2023-03-07 15:31:46.358518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc91765e37f'
down_revision = '29f34eda35d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_time', sa.String(length=100), nullable=True))
        batch_op.drop_column('post_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_date', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('post_time')

    op.create_table('posting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('website_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_company_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_tags', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_description', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('salary_range', sa.VARCHAR(length=100), nullable=True),
    sa.Column('posted_date', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
