"""empty message

Revision ID: 29f34eda35d8
Revises: e3a4057a58ee
Create Date: 2023-03-02 13:03:00.174627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f34eda35d8'
down_revision = 'e3a4057a58ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('website_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_company_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_tags', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_description', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('salary_range', sa.VARCHAR(length=100), nullable=True),
    sa.Column('posted_date', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
