"""empty message

Revision ID: e3a4057a58ee
Revises: 
Create Date: 2023-03-01 23:20:40.454898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a4057a58ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
